services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=payload-empty
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#volumes:
#  pgdata:
